Updated AROMA

diff --git a/tools/efs-backup b/tools/efs-backup
--- a/tools/efs-backup
+++ b/tools/efs-backup
@@ -1,31 +1,38 @@
 #!/tmp/busybox sh
 ## Performs backup of the efs partition
-set -x
+## This script assumes that you already mounted all the necessary partitions
 
 PATH=/tmp:/sbin:$PATH
 BB=/tmp/busybox
 backup_dir=/sdcard/aroma-backup
-efs_device=/dev/block/stl3
+efs_mountpoint=/efs
 efs_backfile=$backup_dir/efs-`$BB date +"%m-%d-%y--%H-%M"`.tar
-tmp_backfile=efs
 
-if $BB test -d $datadir; then
-  $BB test ! -d $backup_dir && $BB mkdir $backup_dir
-  
-  cd /tmp/
-  echo 'Backing up efs'
-  $BB dd if=$efs_device of=$tmp_backfile && \
-  $BB tar cf $efs_backfile $tmp_backfile && \
-  $BB md5sum -t $efs_backfile >> $efs_backfile && \
-  $BB mv $efs_backfile $efs_backfile.md5 && \
-  $BB rm $tmp_backfile
-  
-  if $BB test $? -ne 0; then
-    echo "efs backup failed"
-    exit 1
-  else
-    echo "efs backup completed"
-  fi
-  exit 0
+# Make sure that the aroma backup directory exists
+$BB test ! -d $backup_dir && $BB mkdir $backup_dir
+
+echo 'Backing up efs'
+cd $efs_mountpoint
+
+# We'll store the results of ls, if there are no files it will be blank
+is_empty=`ls $efs_mountpoint`
+
+if [ efs == efs"$is_empty" ]; then
+  # The /efs partition was empty, we're not attempting a backup
+  echo "ERROR: nv_data.bin file not found, backup CANNOT be created, exiting."
+  exit 1
 fi
+
+# We're going to create a tarball of efs, then create an md5sum for it
+$BB tar cf $efs_backfile * && \
+$BB md5sum $efs_backfile > $efs_backfile.md5
+
+# Test to see if the backup succeeded
+if $BB test $? -ne 0; then
+  echo "efs backup failed"
+  exit 1
+else
+  echo "efs backup completed"
+fi
+exit 0
 
